Makefile
README
dnsdb_query.c
ns_ttl.c
ns_ttl.h

this adds before/after support and has been tested by joe. requesting merge.

Beforeafter

---

dnsdb_query.man

Adds a manpage for `dnsdb_query`.

Add dnsdb_c manpage

---

dnsdbq.c
dnsdbq.man

Merge in Info branch

---

dnsdbq.c

use curl_multi_wait more idiomatically

---

dnsdbq.c

libcurl failed since could not resolve the hostname
libcurl failed since could not connect
dnsdbq should exit with a non-zero status in case of curl failure, but that is not implemented (yet).

Print curl failure status returned from curl_multi_info_read, such as:

---

Makefile
dnsdbq.c
dnsdbq.man

…understandable textual form, including converting any epoch integer times into UTC formatted times.

info option variant to pretty-print results, including converting epoch seconds to local time

---

dnsdbq.c
dnsdbq.man

exit with nonzero on database connection errors.

exit with nonzero if a connection error occurs

---

dnsdbq.c
dnsdbq.man

#55 and #56 merged into this.  This needs to merge into master.  Please squash & rebase.

remerge - Issue51 apply limit before sort

---

dnsdbq.man

Clarified case if bailiwick but not rrtype specified. Move bailiwick text to common section. Fixed one typo

Bailiwick documentation

---

dnsdbq.c
dnsdbq.man

Please do not merge until server side ready.

Support skip feature with new -P page_number option.  Improve man page formating

---

dnsdbq.c
dnsdbq.man

Change -R option to be a -N option.  Add a new -R option that searches the left-hand-side.  Reference dnstable-encoding(5).

Issues #92 and #93

---

dnsdbq.c
dnsdbq.man

with some warning and documentation changes

fix #90 with some warning and documentation changes

---

dnsdbq.man

I will move the v1.5.0 tag after this is merged.

document RRset (raw) query.  document HEX better

---

Makefile
dnsdbq.c
pdns_dnsdb.c
pdns_dnsdb.h

Add WANT_PDNS_DNSDB flag to allow DNSDB to be optional

Make dnsdb optional but at least one pdns system required

---

dnsdbq.c
netio.c
netio.h
pdns.h
pdns_circl.c
pdns_dnsdb.c
sort.c

Improve comments and variable names

---

dnsdbq.c
netio.c
pdns.h
pdns_dnsdb.c

Add more comments.
Add some assert() calls.
Fix typo in printf.
Add missing "static"s.
Normalize some formatting.

Minor fixes

---

dnsdbq.c
dnsdbq.man
globals.h

Fail if -r or -n argument is not 7 bit clean unless new -8 switch given.

---

dnsdbq.c
dnsdbq.man
globals.h
netio.c
ns_ttl.c
ns_ttl.h
pdns.c
pdns.h
sort.c
time.c

Duration printing and sorting, V2.2.1

---

dnsdbq.c
globals.h
netio.h
pdns_dnsdb.c

this may be the least lines of code changed solution, but is a not as clean as possible.

Fix issue 154: regression in not allowing -l for a -V summarize

---

README

Equivalent text approved by @softwarehackery and merged into dnsdbflex repo

Added installation instructions

---

README

Just adding a simple example of what a query and result look like once dnsdbq is built

Add example query and output to README

---

README

clarify dnsdb is dnsdb2 and when to use dnsdb1

---

dnsdbq.c
pdns.c
pdns.h

dedup the PDNS JSON presentation (lookup vs. summarize)

---

README
asinfo.c
globals.h

this time from the right branch.

Clarity 256

---

dnsdbq.c

vixie was sloppy and clang didn't save him.

return results must be checked

---

asinfo.c
asinfo.h
pdns.c

alternative fix for issue #198

see if we can remove the need for res_rcode() by changing the error path

---

dnsdbq.c
globals.h
netio.c

based on PR 204, refactor and comment for clarity

---

Makefile
dnsdbq.c
pdns.c
tokstr.c
tokstr.h

institute tokstr

---

dnsdbq.c
pdns.c
tokstr.c
tokstr.h

still revising the tokstr interface; this branch is a waypoint.

attempt to work around gcc11 structure size checks

---

defs.h
globals.h

Needs testing on cygwin on Windows 11

Fix issue 209: error: unknown type ssize_t; did you mean _ssize_t?

---

tokstr.c

"error: unknown type ssize_t; did you mean _ssize_t?"

Revised fix for issue 209: 

---

Makefile
README

in the README for modifying the Makefile.

Can now build on Apple M1 processors by following the instructions

---

dnsdbq.c
globals.h

Issue 214: batch option parsing bug in tokstr library changes.

---

defs.h
dnsdbq.c
dnsdbq.man
globals.h
netio.c
netio.h
pdns.c
pdns.h
pdns_dnsdb.c
time.h

as requested, and tested, by joe st sauver.

add '-T qdetail' to annotate JSON results with the query that generated them (for batching)

---

dnsdbq.c
dnsdbq.man
globals.h
netio.c
pdns.c
pdns_circl.c
pdns_dnsdb.c
sort.c

add -o to set curl connect and request timeouts (in seconds)
add and use my_logf() to normalize warning reporting

Timeout control, as requested by Joe St Sauver

---

globals.h
time.c

fix printf format problem on machines with long tv_usec; version 2.6.7

---

time.c

Corrected math operator used.
Authored-by: Moshe Waitzman <mwaitzman@outlook.com>

fix time value calculations
