dnsdb/dnsdbq

Makefile, README
This fixes a typo and makes dnsdb_c compile and work on OSX.
=> OSX compatibility

dnsdbq.man
Documented that APIKEY can also be used as an environment variable, but as secondary to DNSDB_API_KEY
=> APIKEY as env variable

dnsdbq.c, dnsdbq.man
Clarified meaning of: usage("-k !< {first,last,count}");
Don't allow multiple -k options (each overwrote previous), but that might have been done
by a user wanting multiple sort fields.  Remind user to use comma to separate multiple
sort fields.
Resorted the options listed in the man page.
Removed duplicate -h option in man page.
=> Fix internal help message for -k option.  Sort man page

dnsdbq.c, dnsdbq.man
Added -R raw_data option to allow specifying raw rdata queries.
Disallow specifying rrtype both with -t and after a slash in -n and -r options.
Disallow specifying bailiwick both with -b and after a second slash in -r options.
Renamed "type" variable to the more explicit "rrtype" variable.
Clarified in man page that the -t option specifies an rrtype, not a query type.
=> Support raw rdata queries and associated clean up

dnsdbq.c, dnsdbq.man
I implemented both options in the issue.  The first commit just does the first option.  The second commit adds the second.  The commit message for the second commit shows the differences in behavior.  You have the choice to accept neither commit, the first, or both.
=> Issue51 apply limit before sort

dnsdbq.c
The following now give identical output, as desired:
```
$ dnsdbq -s -k count -r bbn.com -j -l 100 | head -2
$ dnsdbq -s -k count -r bbn.com -j -l 100 -L 2
```
=> Fix output limit when sorting the output

dnsdbq.c
Handles case where only a bailiwick filter is given for an rrset query by using rrtype ANY.
dnsdbq previously ignored the bailiwick filter if no rrtype was given.
=> Apply bailiwick filter when rrtype is not specified.

dnsdbq.c, dnsdbq.man
when we changed the logic to not use -r on POSIX sort, but to instead add the "r" qualifier to all keys, we forgot to ensure that there would be at least one key. so, the default for -k is now first,last,count, if -s or -S is given. also one small man page change.
=> make -s/-S work even if -k is not specified

LICENSE, dnsdbq.c, dnsdbq.man
* Added -V verb flag, which defaults to the classic "lookup" verb, but also supports the new summarize flag.
* Logic change: if -b or -t are specified then -r cannot contain a slash.
* Document and add Warning: -t option should be before the -R, -r, or -n options.
* Use strtol instead of atol for integers that might be very large.
* Pretty-print offset_max value from a rate_limit call.
* Add "-M max_count" flag to control stopping a summarize upon reaching that max_count.
* Handle large offset values without going negative.
* Improved -h display: Sorted the expanded options.  More uniform formatting.
* Validate that a verb is supported by a pDNS system.  Improve circl path validation.
* Add -O offset.
* Use -u on sort to prevent duplicate answers when making multiple upst<E2><80><A6> …
=> dnsdbq july2019 updates

dnsdbq.man
- clean up other formatting of enumerated items that don't need to be enumerated.
- fix one formatting bug.
=> Document that csv format is information losing.

dnsdbq.c
Otherwise:
$ dnsdbq -r 'foo/./ANY' -d -d -d
is converted to URL:  https://api.dnsdb.info/lookup/rrset/name/foo/ANY
but it should be URL: https://api.dnsdb.info/lookup/rrset/name/foo/./ANY
=> Use CURLOPT_PATH_AS_IS option if it is available.

dnsdbq.man
In man page: 
Remove duplicate -v flag description.
Move -q flag to be in alphabetical order
=> more man page fixes

dnsdbq.c
previously `-l foo` or `-L foo` was not treated as an error
=> Change parsing -l and -L to use parse_long so it will catch parsing errors

dnsdbq.c
`dnsbq -v` output was:
`dnsdbq: dnsdbq version 1.5`
now will be:
`dnsdbq: version 1.5`
=> Remove redundant program name in -v output

dnsdbq.c
Fix typo in parsing the config file: "dnsdn" should be "dnsdb"
=> Fix typo: dnsdn should be dnsdb

netio.c
`dnsdbq -t A -r 'fsi.io' -l 0 -j` was not outputting anything.
-l 0 set the query limit and the output limit to 0, but the old code below thought we reached the output limit.
`-               if (sorting == no_sort && output_limit != -1 &&`
`+               if (sorting == no_sort && output_limit > 0 &&`
=> Handle limit 0

dnsdbq.c, globals.h, pdns_dnsdb.c
Test for null psys before destroying it.  Rename variable for understandability
=> Query parameters were not copied into the query struct. 

dnsdbq.c
In the case of non-Linux systems, a build will fail because of an undeclared variable (`optreset`). This PR removes the reference to that undeclared variable to facilitate building on all supported architectures. At least in Debian it now also builds on the kFreeBSD- and Hurd-based variants (https://buildd.debian.org/status/package.php?p=dnsdbq).
=> remove undeclared variable

dnsdbq.c
This is a stray branch.  It looks fine to me to merge.
=> when adding O: to QPARAM_OPTS, it has to be removed from the other getopt options

dnsdbq.man
because I've gotten multiple questions about this variable not working, when really the wrong output format was specified.
=> Clarify when DNSDBQ_TIME_FORMAT is useful

netio.c
still does print an error message if applicable, such as "Query status: ERROR (Error: Bad API key)"
=> For an info command, do not output "Query status: NOERROR (no results found for query.)" when successful

netio.c
We need it for a feature test for a feature from 7.42.0.
CURL_AT_LEAST_VERSION was introduced in 7.43.0.
Therefore, if we build against 7.42.0 then we won't use the CURLOPT_PATH_AS_IS feature.
This is a small bug but 7.42.0 is from 2015.
=> Make sure CURL_AT_LEAST_VERSION is defined before using it.

dnsdbq.c
The json output files are in bare format, not SAF.  
Also read in as much as our buffer can hold
=> Regression: Fix -J mode

Makefile, asinfo.c, asinfo.h, defs.h, dnsdbq.c, pdns.c
An alternative to CRIPPLED_LIBC is to use CYGWIN.
An advantage is the Makefile need not be edited to compile on cygwin.
=> Cygwin revised2

netio.c, pdns.c, pdns.h, pdns_dnsdb.c, sort.c
greatly simplify sortable_dnsname(), and fix an assertion there.
add nalnum to struct counted, for use by the above.
make tup->obj.rrname immutable, and have only tup->rrname subject to transforms.
=> Domainsort

dnsdbq.man
-c   by default, -A and -B (separately or together) will select partial over-
laps of database tuples and time search criteria. To match only com-
pletely bracketed tuples, add the -c ("completeness") flag (this is also
known as "strict" mode). Can only be specified once, and for reasons of
geometry, affects both -A and -B if both are specified.
=> clarify relationship of -c to -A/-B, in both main text and examples

dnsdbq.c, netio.c, ns_ttl.c, pdns.c, pdns.h, pdns_circl.c, pdns_dnsdb.c, sort.c, time.c
Improve comments in struct pdns_system.  Make one typedef more consistent.
Use return X; consistently, rather than a mix with return (X);
=> minor cleanups

Makefile, deduper.c, deduper.h, defs.h, dnsdbq.c, dnsdbq.man, globals.h, netio.c, netio.h, pdns.c, pdns.h, pdns_dnsdb.c
add new -p option, 'minimal'. this emits only unique keys or values, one per line, for use by shell scripts. also killed some lint.
=> add '-p minimal', becomes V2.5.7

deduper.c
The use of `lu` to format a `size_t` leads to build failures (via `-Werror`) on many architectures. See example from a Debian build for ARM below.
```
cc -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-result  -g -O3 -W -Wall -Wextra -Wcast-qual -Wpointer-arith -Wwrite-strings -Wmissing-prototypes  -Wbad-function-cast -Wnested-externs -Wunused -Wshadow -Wmissing-noreturn -Wswitch-enum -Wconversion -Werror -DWANT_PDNS_DNSDB=1 -DWANT_PDNS_CIRCL=1 -Wdate-time -D_FORTIFY_SOURCE=2 `curl-config --cflags`  -I/usr/local/include -c deduper.c
deduper.c: In function ‘deduper_dump’:
deduper.c:90:42: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ {aka ‘unsigned int’} [-Werror=format=] …
```
=> use 'zu' format string in deduper_dump()

dnsdbq.c, globals.h
Update version to 2.6.1
(Reported by Boris)
=> ctype.h functions require int arguments.  cygwin gcc enforces this.

dnsdbq.c, pdns.c
we use strtok_r() everywhere else, but a few strsep()'s have crept in over time.
=> use strtok_r() in preference to strsep(), for consistency and modernity

tokstr.c, tokstr.h
revise api to communicate in terms of regions. null terminated input and output strings are still available (strndup), but so is zero-copy and copy. this completes the processing of reviews garnered on codereview.stackexchange.com.
=> tokstr regions

README
Added dependencies for a successful build on Amazon Linux to the README file
=> Add build dependencies for Amazon Linux 2023

README
CentOS 8 steps also works for AlmaLinux & Rocky Linux. And reformat to one single dnf line.
=> Update README - CentOS 8 steps also works for AlmaLinux & Rocky Linux

dnsdbq.c, dnsdbq.man, globals.h, netio.c
there exist cookie-based authentication schemes, make sure dnsdbq can access them.
=> add -C option to select a cookie jar file for libcurl

defs.h, globals.h, time.c, time.h
needed better resolution on time stamps to suss out performance limits.
=> display millisecond-granularity timestamps in logging and debugging
